### ISSUE TITLE
[BUG] Problems with plugins

### ISSUE THREAD

**Issue by Kennar** [magmafoundation/Magma#18]
The engine has several shortcomings in classes and methods, here are plugins that have problems on magma, any other engine works without a problem:

1. ProtocolLib: https://pastebin.com/NLr3C7iY
    Version:  v4.4.0
2. CrateReloaded: https://pastebin.com/0TwF6ive
    Version: v2.0.11
3. PlaceholderAPI: https://pastebin.com/HCyL4aB4
    Version: v2.10.4
4. StoneTreasures: https://pastebin.com/NmNizG2r
    Version:  v2.8.0
5. OpenInv: https://pastebin.com/xncRayiF
    Version: v3.3.3 (After entering the command or opening the chests)

There is also a problem with player verification, when the player exits the lobby too quickly to the server there is a skin error. Occurs only on the Magma engine.
We use the bungeecord plugin: Bungee 1.7.x - 1.13 | Premium Authenticator
Error: https://pastebin.com/azHzvrVZ

- Magma Version: Magma-a3e77ec-server

**Comment by Hexeption** [comment]
Most of these should be fixed in the NMS update coming out very shortly

**Comment by Kennar** [comment]
And when can you expect it? Because we care about time, because we plan to open the server within a week. We will be very grateful for your quick help.

**Comment by Hexeption** [comment]
in the next week or so we are currently testing and a few bugs to fix but should be very very soon

**Comment by Kennar** [comment]
If this is not a problem, we can help with testing and checking.
At the same time, we will be able to test our server before opening

**Comment by Hexeption** [comment]
it's unusable at this time as nms plugins don't register commands.

We are working on finding a solution on registering the commands once this has been fixed we will push a version out as soon as possible.

**Comment by Kennar** [comment]
In that case I'm waiting, I hope you can fix it quickly :)

**Comment by Hexeption** [comment]
Thanks for your patience and your support <3

**Comment by Hexeption** [comment]
All problems fixed in NMS update

**Comment by Kennar** [comment]
The issue still exists:  Player verification, when the player exits the lobby too quickly to the server there is a skin error. Occurs only on the Magma engine.
We use the bungeecord plugin: Bungee 1.7.x - 1.13 | Premium Authenticator
Error: https://pastebin.com/azHzvrVZ
