### ISSUE TITLE
[BUG] building Advanced Rocketry rockets crashes server

### ISSUE THREAD

**Issue by wesleytech** [magmafoundation/Magma#182]
description
on my server (running magma and the enigmatica 2 expert skyblock pack) i've got an issue where if i make a rocket my server crashes.

to reproduce:
1. make a rocket (from advanced rocketry and on a server running magma!)
2. build the rocket
3. crash

expected behavior: 
it should behave like on singleplayer, meaning it doesnt crash.

crash log:
https://paste.forgottenmc.net/mohutumile.rb

info:
mod name: advanced rocketry 
mod version: 1.7.0-208-universal
mod pack: Enigmatica 2 expert skyblock
mod pack version: 1.35 
magma version: 44e91f6
OS: petrodactyl panel running on Ubuntu 18.04.4 LTS

**Comment by IGCBOOM** [comment]
Can confirm this is happening for me as well on 93c02978d56502a0c4a7c51a847deac6967f0991

**Comment by wesleytech** [comment]
can confirm this is also happening on Magma-1.12.2-Paper-Full-API-Dev-Build.2.jar

**Comment by kwright02** [comment]
It seems there is an issue when trying to use the Rocketry's Dummy World with Craft bukkit events. I will be looking into a potentia fix for this as I think I know a workaround for it. Otherwise we may have to label this incompatible. i will re-comment when I have more info

**Comment by kwright02** [comment]
This is now fixed in the newest release.

**Comment by nacjm** [comment]
I hate to point this out but it seems this isn't entirely fixed. When leaving the game while inside the space dimension for Rocketry and trying to rejoin you get kicked with fatal errors until your playerdata is reset thus resulting in you no longer being in the dimension

**Comment by Amgelo563** [comment]
Looks like another unrelated issue that just happened to be with the same mod tho, I think it'd be great if you can open another issue with logs, details, etc.
